apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-nginx
resources:
  - ../../base/nginx
replicas:
  - name: nginx
    count: 2
commonLabels:
  environment: staging-nginx