apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-nginx
resources:
  - ../../base/nginx
  - ingress.yaml
replicas:
  - name: nginx
    count: 3
patches:
  - path: configmap-patch.yaml
commonLabels:
  environment: prod-nginx