apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev-nginx
resources:
  - ../../base/nginx
  - ingress.yaml
patches:
  - path: configmap-patch.yaml
replicas:
  - name: nginx
    count: 2
commonLabels:
  environment: dev-nginx